workflows:
  ios-development-build:
    name: iOS Development Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      apple: Codemagic API Key  # ← Usa exactamente el nombre que pusiste al crear la key (en tu caso "Codemagic API Key")
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter packages pub get
      - name: Install CocoaPods
        script: |
          cd ios && pod install && cd ..
      - name: Build iOS
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - lacasaverdeac@gmail.com  # ← tu email real