workflows:
  ios-development-build:
    name: iOS Development Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      apple: Codemagic API Key  # ← EL NOMBRE EXACTO que te dio Codemagic para la integración Apple (ej: "lacasaverdeac@gmail.com - Developer Portal")
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          cd ios && pod install && cd ..
      - name: Set up signing
        script: |
          xcode-project use-profiles
      - name: Build iOS
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - lacasaverdeac@gmail.com  # ← tu email real